# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'slab_new.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from pylayers.gis.layout import *
from pylayers.antprop.slab import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog, QTextEdit, QMainWindow, QAction
from PyQt5.QtGui import QIcon
from pathlib import Path


class Ui_Slab(object):
    def __init__(self):
        self.S = SlabDB("slabDB.ini")
        
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(589, 420)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 90, 421, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.thick_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.thick_2.setObjectName("thick_2")
        self.gridLayout_2.addWidget(self.thick_2, 2, 2, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_4, 4, 1, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_2.addWidget(self.doubleSpinBox_3, 3, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_2.addWidget(self.doubleSpinBox_2, 2, 3, 1, 1)
        self.material_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.material_1.setObjectName("material_1")
        self.gridLayout_2.addWidget(self.material_1, 1, 0, 1, 1)
        self.thick_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.thick_4.setObjectName("thick_4")
        self.gridLayout_2.addWidget(self.thick_4, 4, 2, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_1, 1, 1, 1, 1)
        self.thick_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.thick_3.setObjectName("thick_3")
        self.gridLayout_2.addWidget(self.thick_3, 3, 2, 1, 1)
        self.name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.name.setObjectName("name")
        self.gridLayout_2.addWidget(self.name, 0, 0, 1, 1)
        self.material_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.material_3.setObjectName("material_3")
        self.gridLayout_2.addWidget(self.material_3, 3, 0, 1, 1)
        self.thick_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.thick_1.setObjectName("thick_1")
        self.gridLayout_2.addWidget(self.thick_1, 1, 2, 1, 1)
        self.material_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.material_4.setObjectName("material_4")
        self.gridLayout_2.addWidget(self.material_4, 4, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_1.setObjectName("doubleSpinBox_1")
        self.gridLayout_2.addWidget(self.doubleSpinBox_1, 1, 3, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_2.addWidget(self.doubleSpinBox_4, 4, 3, 1, 1)
        self.material_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.material_2.setObjectName("material_2")
        self.gridLayout_2.addWidget(self.material_2, 2, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 201, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 330, 421, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Slab_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Slab_Button.setObjectName("Slab_Button")
        self.horizontalLayout.addWidget(self.Slab_Button)
        self.SlabDB_Button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SlabDB_Button.setObjectName("SlabDB_Button")
        self.horizontalLayout.addWidget(self.SlabDB_Button)
        self.SaveButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.SaveButton.setObjectName("SaveButton")
        self.horizontalLayout.addWidget(self.SaveButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        self.Slab_Button.clicked.connect(self.pop_box_slab)
        self.SlabDB_Button.clicked.connect(self.pop_box_slabDB)
        self.SaveButton.clicked.connect(self.save)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.thick_2.setText(_translate("Dialog", "thick2"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "ABSORBENT"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "AIR"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "BRICK"))
        self.comboBox_4.setItemText(4, _translate("Dialog", "PLASTER"))
        self.comboBox_4.setItemText(5, _translate("Dialog", "CONCRETE"))
        self.comboBox_4.setItemText(6, _translate("Dialog", "REINFORCED_CONCRETE"))
        self.comboBox_4.setItemText(7, _translate("Dialog", "WOOD"))
        self.comboBox_4.setItemText(8, _translate("Dialog", "SEA_WATER"))
        self.comboBox_4.setItemText(9, _translate("Dialog", "STONE"))
        self.comboBox_4.setItemText(10, _translate("Dialog", "PLATRE-57GHz"))
        self.comboBox_4.setItemText(11, _translate("Dialog", "CONCRETE_TC1_METIS"))
        self.comboBox_4.setItemText(12, _translate("Dialog", "WOOD_TC1_METIS"))
        self.comboBox_4.setItemText(13, _translate("Dialog", "METAL"))
        self.comboBox_4.setItemText(14, _translate("Dialog", "CONCRETE_IC1004"))
        self.comboBox_4.setItemText(15, _translate("Dialog", "WET_EARTH_IC1004"))
        self.comboBox_4.setItemText(16, _translate("Dialog", "WALL_TC2_METIS"))
        self.material_1.setText(_translate("Dialog", "material1       "))
        self.thick_4.setText(_translate("Dialog", "thick4"))
        self.comboBox_1.setItemText(1, _translate("Dialog", "ABSORBENT"))
        self.comboBox_1.setItemText(2, _translate("Dialog", "AIR"))
        self.comboBox_1.setItemText(3, _translate("Dialog", "BRICK"))
        self.comboBox_1.setItemText(4, _translate("Dialog", "PLASTER"))
        self.comboBox_1.setItemText(5, _translate("Dialog", "CONCRETE"))
        self.comboBox_1.setItemText(6, _translate("Dialog", "REINFORCED_CONCRETE"))
        self.comboBox_1.setItemText(7, _translate("Dialog", "WOOD"))
        self.comboBox_1.setItemText(8, _translate("Dialog", "SEA_WATER"))
        self.comboBox_1.setItemText(9, _translate("Dialog", "STONE"))
        self.comboBox_1.setItemText(10, _translate("Dialog", "PLATRE-57GHz"))
        self.comboBox_1.setItemText(11, _translate("Dialog", "CONCRETE_TC1_METIS"))
        self.comboBox_1.setItemText(12, _translate("Dialog", "WOOD_TC1_METIS"))
        self.comboBox_1.setItemText(13, _translate("Dialog", "METAL"))
        self.comboBox_1.setItemText(14, _translate("Dialog", "CONCRETE_IC1004"))
        self.comboBox_1.setItemText(15, _translate("Dialog", "WET_EARTH_IC1004"))
        self.comboBox_1.setItemText(16, _translate("Dialog", "WALL_TC2_METIS"))
        self.thick_3.setText(_translate("Dialog", "thick3"))
        self.name.setText(_translate("Dialog", "name"))
        self.material_3.setText(_translate("Dialog", "material3"))
        self.thick_1.setText(_translate("Dialog", "thick 1      "))
        self.material_4.setText(_translate("Dialog", "material4"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "ABSORBENT"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "AIR"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "BRICK"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "PLASTER"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "CONCRETE"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "REINFORCED_CONCRETE"))
        self.comboBox_2.setItemText(7, _translate("Dialog", "WOOD"))
        self.comboBox_2.setItemText(8, _translate("Dialog", "SEA_WATER"))
        self.comboBox_2.setItemText(9, _translate("Dialog", "STONE"))
        self.comboBox_2.setItemText(10, _translate("Dialog", "PLATRE-57GHz"))
        self.comboBox_2.setItemText(11, _translate("Dialog", "CONCRETE_TC1_METIS"))
        self.comboBox_2.setItemText(12, _translate("Dialog", "WOOD_TC1_METIS"))
        self.comboBox_2.setItemText(13, _translate("Dialog", "METAL"))
        self.comboBox_2.setItemText(14, _translate("Dialog", "CONCRETE_IC1004"))
        self.comboBox_2.setItemText(15, _translate("Dialog", "WET_EARTH_IC1004"))
        self.comboBox_2.setItemText(16, _translate("Dialog", "WALL_TC2_METIS"))
        self.material_2.setText(_translate("Dialog", "material2"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "ABSORBENT"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "AIR"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "BRICK"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "PLASTER"))
        
        self.comboBox_3.setItemText(5, _translate("Dialog", "CONCRETE"))
        self.comboBox_3.setItemText(6, _translate("Dialog", "REINFORCED_CONCRETE"))
        self.comboBox_3.setItemText(7, _translate("Dialog", "WOOD"))
        self.comboBox_3.setItemText(8, _translate("Dialog", "SEA_WATER"))
        self.comboBox_3.setItemText(9, _translate("Dialog", "STONE"))
        self.comboBox_3.setItemText(10, _translate("Dialog", "PLATRE-57GHz"))
        self.comboBox_3.setItemText(11, _translate("Dialog", "CONCRETE_TC1_METIS"))
        self.comboBox_3.setItemText(12, _translate("Dialog", "WOOD_TC1_METIS"))
        self.comboBox_3.setItemText(13, _translate("Dialog", "METAL"))
        self.comboBox_3.setItemText(14, _translate("Dialog", "CONCRETE_IC1004"))
        self.comboBox_3.setItemText(15, _translate("Dialog", "WET_EARTH_IC1004"))
        self.comboBox_3.setItemText(16, _translate("Dialog", "WALL_TC2_METIS"))
        self.label.setText(_translate("Dialog", "customized SlabDB"))
        self.label_2.setText(_translate("Dialog", "add new slab to DataBase"))
        self.Slab_Button.setText(_translate("Dialog", "create a Slab"))
        self.Slab_Button.setToolTip("you can create a slab, which is a sequence of layers which have a given width and a given material from the material DB")
        self.SlabDB_Button.setText(_translate("Dialog", "Preview of SlabDb"))
        self.SlabDB_Button.setToolTip("you can create a new slab database by adding some new slabs to the inital slab database")
        self.SaveButton.setText(_translate("Dialog", "Save SlabDB"))
        self.SaveButton.setToolTip("you can save the new created database")


   
    def pop_box_slab(self):
        name = self.lineEdit.text()
        if name == '':
            self.pop_error2()
        else:
            material_1 = self.comboBox_1.currentText()
            material_2 = self.comboBox_2.currentText()
            material_3 = self.comboBox_3.currentText()
            material_4 = self.comboBox_4.currentText()
            thick_1 = self.doubleSpinBox_1.value()
            thick_2 = self.doubleSpinBox_2.value()
            thick_3 = self.doubleSpinBox_3.value()
            thick_4 = self.doubleSpinBox_4.value()
            material_list = []
            thick_list = []
            if material_1 != '':
                material_list.append(material_1)
                thick_list.append(thick_1)
                if material_2 != '':
                    material_list.append(material_2)
                    thick_list.append(thick_2)
                    if material_3 != '':
                        material_list.append(material_3)
                        thick_list.append(thick_3)
                        if material_4 != '':
                            material_list.append(material_4)
                            thick_list.append(thick_4)
            if thick_list == []:
                self.pop_error()
            else:
                self.S.add(name,material_list,thick_list)
                self.msg = QMessageBox()
                self.msg.setIcon(QMessageBox.Information)
                self.msg.setText(str(self.S[name]))
                self.msg.setInformativeText("This is new created slab")
                self.msg.setWindowTitle("new slab")
                self.msg.setDetailedText("The details are as follows:")
                x = self.msg.exec()

    def pop_box_slabDB(self):
        self.msg = QMessageBox()
        self.msg.setIcon(QMessageBox.Information)
        self.msg.setText(str(self.S.keys()))
        self.msg.setInformativeText("This is new created slabDB")
        self.msg.setWindowTitle("new slabDB")
        self.msg.setDetailedText("The details are as follows:")
        
        x = self.msg.exec()
    
    def save(self):
        name_tup = QFileDialog.getSaveFileName(None, "Save file", "", ".slab")
        name = ''.join(name_tup)
        file = open(name,'w')
        self.S.save(_fileini='test_slabDB.ini')
        text = open('/home/lijiaqian/pylayers_project/ini/test_slabDB.ini')
        for line in text.readlines():
            file.write(line)
        text.close
        file.close  
        
    def pop_error(self):
        self.msg = QMessageBox()
        self.msg.setIcon(QMessageBox.Information)
        self.msg.setText('please give input')
        self.msg.setInformativeText("There is an error")
        self.msg.setWindowTitle("Error!")
        x = self.msg.exec()
        
    def pop_error2(self):
        self.msg = QMessageBox()
        self.msg.setIcon(QMessageBox.Information)
        self.msg.setText('please give name of this slab')
        self.msg.setInformativeText("There is an error")
        self.msg.setWindowTitle("Error!")
        x = self.msg.exec()
        

if __name__ == "__main__":
    import sys
    from pylayers.gis.layout import *
    from pylayers.antprop.slab import *
    from PyQt5 import QtCore, QtGui, QtWidgets
    from PyQt5.QtWidgets import QMessageBox, QFileDialog, QTextEdit, QMainWindow, QAction
    from PyQt5.QtGui import QIcon
    from pathlib import Path
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())